-
  name: 'Query and save to file each site info'
  hosts: check_mk_sites
  vars:
    carpeta_reportes: "{{carpeta_reportes}}"
  tasks:
    -
      name: "Create Localhost temp folder for saving each query in separate files"
      file:
        path: "{{carpeta_reportes}}"
        state: directory
      delegate_to: localhost

    -
      name: 'Query each site and save result in a variable'
      shell: 
        cmd: |
          printf "GET services\nColumns: host_name description state\nOutputFormat: csv\n" | sudo -u {{site_name}} /omd/sites/{{site_name}}/bin/unixcat /omd/sites/{{site_name}}/tmp/run/live
      args:
        executable: /bin/bash 
      register: reporte

    -
      name: "Copying Query Result into temporal files"
      copy:
        content: "{{reporte.stdout_lines}}"
        dest: "{{carpeta_reportes}}/reporteSalidaServicios{{site_name}}.txt"
      delegate_to: localhost

    -
      name: "Cleaning and formating result for generate csv"
      shell: cat {{carpeta_reportes}}/reporteSalidaServicios{{site_name}}.txt | sed 's/, /\n/g' | sed 's/"//g' | sed 's/\[//g' | sed 's/\]//g' | awk '{print $0 ";{{site_name}}"}' > {{carpeta_reportes}}/reporteProcesado{{site_name}}.csv
      delegate_to: localhost
      register: procesado

    -
      name: "Merge all temporal files to newone"
      shell: cat {{carpeta_reportes}}/reporteProcesado* > {{carpeta_reportes}}/reportefinal.csv 
      delegate_to: localhost
      
    -
      name: "Adding head titles to final csv report"
      shell: sed '1ihostname;servicio;estado;site' {{carpeta_reportes}}/reportefinal.csv > {{carpeta_reportes}}/reportefinalcabecera.csv
      delegate_to: localhost

-
  name: 'Copying final csv report to remote webserver'
  hosts: webserver
  vars:
    carpeta_destino: "/var/www/html/reporte/reporte"
  tasks:
    -
      name: 'Copying File'
      copy:
        src: {{carpeta_reportes}}/reportefinalcabecera.csv
        dest: "{{carpeta_destino}}/reporte.csv"
        owner: apache
        group: apache
        mode: '644'

